/*
 * Tsuru API
 * Tsuru API integration to other external clients (only partial, not all endpoints)
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.tsuru.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import io.tsuru.client.model.Lock;
import io.tsuru.client.model.Router;

import java.util.ArrayList;
import java.util.List;

/**
 * Application
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-29T00:11:08.586Z")
public class Application {
  @SerializedName("description")
  private String description = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("plan")
  private Plan plan = null;

  @SerializedName("platform")
  private String platform = null;

  @SerializedName("pool")
  private String pool = null;

  @SerializedName("routers")
  private List<Router> routers = null;

  @SerializedName("tags")
  private List<String> tags = null;

  @SerializedName("teamowner")
  private String teamOwner = null;

  @SerializedName("ip")
  private String ip = null;

  @SerializedName("cname")
  private List<String> cname = null;

  @SerializedName("lock")
  private Lock lock = null;

  public List<Router> getRouters() {
    return routers;
  }

  public void setRouters(List<Router> routers) {
    this.routers = routers;
  }

  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public Lock getLock() {
    return lock;
  }

  public void setLock(Lock lock) {
    this.lock = lock;
  }

  public List<String> getCname() {
    return cname;
  }

  public void setCname(List<String> cname) {
    this.cname = cname;
  }


  public Application description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Application name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Application plan(Plan plan) {
    this.plan = plan;
    return this;
  }

   /**
   * Get plan
   * @return plan
  **/
  @ApiModelProperty(value = "")
  public Plan getPlan() {
    return plan;
  }

  public void setPlan(Plan plan) {
    this.plan = plan;
  }

  public Application platform(String platform) {
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @ApiModelProperty(value = "")
  public String getPlatform() {
    return platform;
  }

  public void setPlatform(String platform) {
    this.platform = platform;
  }

  public Application pool(String pool) {
    this.pool = pool;
    return this;
  }

   /**
   * Get pool
   * @return pool
  **/
  @ApiModelProperty(value = "")
  public String getPool() {
    return pool;
  }

  public void setPool(String pool) {
    this.pool = pool;
  }

  public Application router(List<Router> router) {
    this.routers = router;
    return this;
  }

   /**
   * Get router
   * @return router
  **/
  @ApiModelProperty(value = "")
  public List<Router> getRouter() {
    return routers;
  }

  public void setRouter(List<Router> router) {
    this.routers = router;
  }

  public Application tag(List<String> tag) {
    this.tags = tag;
    return this;
  }

  public Application addTagItem(String tagItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagItem);
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(value = "")
  public List<String> getTag() {
    return tags;
  }

  public void setTag(List<String> tag) {
    this.tags = tag;
  }

  public Application teamOwner(String teamOwner) {
    this.teamOwner = teamOwner;
    return this;
  }

   /**
   * Get teamOwner
   * @return teamOwner
  **/
  @ApiModelProperty(value = "")
  public String getTeamOwner() {
    return teamOwner;
  }

  public void setTeamOwner(String teamOwner) {
    this.teamOwner = teamOwner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.description, application.description) &&
        Objects.equals(this.name, application.name) &&
        Objects.equals(this.plan, application.plan) &&
        Objects.equals(this.platform, application.platform) &&
        Objects.equals(this.pool, application.pool) &&
        Objects.equals(this.routers, application.routers) &&
        Objects.equals(this.tags, application.tags) &&
        Objects.equals(this.teamOwner, application.teamOwner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, plan, platform, pool, routers, tags, teamOwner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    pool: ").append(toIndentedString(pool)).append("\n");
    sb.append("    router: ").append(toIndentedString(routers)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tags)).append("\n");
    sb.append("    teamOwner: ").append(toIndentedString(teamOwner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

