/*
 * Tsuru API
 * Tsuru API integration to other external clients (only partial, not all endpoints)
 *
 * OpenAPI spec version: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.tsuru.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Deployments
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-29T19:35:39.999Z")
public class Deployments {
  /*
  {

    "ID":"5b8a8b25a51f580001d51231",
    "App":"commons",
    "Timestamp":"2018-09-01T12:50:45.043Z",
    "Duration":88382000000,
    "Commit":"",
    "Error":"---- ERROR during deploy: ----\ninvalid pod phase \"Failed\" - last event: Started container",
    "Image":"",
    "Log":"",
    "User":"jenkins@trustyou.net",
    "Origin":"git",
    "CanRollback":false,
    "RemoveDate":"0001-01-01T00:00:00Z",
    "Diff":"",
    "Message":"GIT_COMMIT : 0825e57ae24f8cc9c5e5321cc2f49de2f295e44d\nGIT_BRANCH : tsuru-files\n"

},
   */

  @SerializedName("ID")
  private String id = null;

  @SerializedName("App")
  private String app = null;

  @SerializedName("Timestamp")
  private String timestamp = null;

  @SerializedName("Duration")
  private String duration = null;

  @SerializedName("Commit")
  private String commit = null;

  @SerializedName("Error")
  private String error = null;

  @SerializedName("Image")
  private String image = null;

  @SerializedName("Log")
  private String log = null;

  @SerializedName("User")
  private String user = null;

  @SerializedName("Origin")
  private String origin = null;

  @SerializedName("CanRollback")
  private Boolean canrollback = false;

  @SerializedName("RemoveDate")
  private String removeDate = null;

  @SerializedName("Diff")
  private String diff = null;

  @SerializedName("Message")
  private String message = null;


  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getApp() {
    return app;
  }

  public void setApp(String app) {
    this.app = app;
  }

  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public String getCommit() {
    return commit;
  }

  public void setCommit(String commit) {
    this.commit = commit;
  }

  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public String getLog() {
    return log;
  }

  public void setLog(String log) {
    this.log = log;
  }

  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public String getOrigin() {
    return origin;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }

  public Boolean getCanrollback() {
    return canrollback;
  }

  public void setCanrollback(Boolean canrollback) {
    this.canrollback = canrollback;
  }

  public String getRemoveDate() {
    return removeDate;
  }

  public void setRemoveDate(String removeDate) {
    this.removeDate = removeDate;
  }

  public String getDiff() {
    return diff;
  }

  public void setDiff(String diff) {
    this.diff = diff;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }
}

